### ISSUE TITLE
项目跑不起来啊→_→

### ISSUE THREAD

**Issue by kdwycz** [JXNU-ACS/ACS-Website#4]
下午在首页看到了有代码提交,就clone下来看看.结果跑不起来

看了下应该是你们想换mysql库,然而``requirements.txt``里面的库和``config.py``连接数据库使用的mysql库不是同一个于是就报错了

还有``.idea``没有进``.gitignore``以及槽点颇多的不遵循[PEP8](https://my.oschina.net/u/1433482/blog/464444)规范的代码

**Comment by william-tu** [comment]
应该是少添加了一个依赖，我改了一下

**Comment by kdwycz** [comment]
![LGTM](http://www.lgtm.in/p/ACilF315q)
